FROM python:3.7-stretch
RUN python3 -m pip install -U scikit-learn pandas scipy numpy gunicorn flask
RUN python3 -m pip install -U implicit lightgbm catboost
RUN python3 -m pip install -U feather-format
RUN pip install -U faiss-cpu
